Task 1 – Unit Conversion Program

In [3]:
def convert_units():
    """
    Converts between different measurement units.

    The function asks the user to select a conversion type
    (length, weight, volume), takes the numeric value, performs
    the conversion and prints the result.

    Handles invalid inputs using try-except.
    """

    try:
        print("Choose conversion type:")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")

        choice = int(input("Enter choice (1/2/3): "))
        value = float(input("Enter value to convert: "))

        if choice == 1:
            print("1. Meter to Feet")
            print("2. Feet to Meter")
            sub = int(input("Select conversion: "))

            if sub == 1:
                result = value * 3.28084
                print(f"{value} meters = {result:.2f} feet")

            elif sub == 2:
                result = value / 3.28084
                print(f"{value} feet = {result:.2f} meters")

            else:
                print("Invalid length option")

        elif choice == 2:
            print("1. Kilogram to Pound")
            print("2. Pound to Kilogram")
            sub = int(input("Select conversion: "))

            if sub == 1:
                result = value * 2.20462
                print(f"{value} kg = {result:.2f} pounds")

            elif sub == 2:
                result = value / 2.20462
                print(f"{value} pounds = {result:.2f} kg")

            else:
                print("Invalid weight option")

        elif choice == 3:
            print("1. Liter to Gallon")
            print("2. Gallon to Liter")
            sub = int(input("Select conversion: "))

            if sub == 1:
                result = value * 0.264172
                print(f"{value} liters = {result:.2f} gallons")

            elif sub == 2:
                result = value / 0.264172
                print(f"{value} gallons = {result:.2f} liters")

            else:
                print("Invalid volume option")

        else:
            print("Invalid conversion type")

    except ValueError:
        print("Invalid input. Please enter numeric values.")


convert_units()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter choice (1/2/3): 2
Enter value to convert: 75
1. Kilogram to Pound
2. Pound to Kilogram
Select conversion: 1
75.0 kg = 165.35 pounds


Task 4.1 (Part 2) — List Operations

In [4]:
def list_sum(numbers):
    """Returns the sum of numbers in a list."""
    return sum(numbers)

def list_average(numbers):
    """Returns the average of numbers in a list."""
    return sum(numbers) / len(numbers)

def list_max(numbers):
    """Returns the maximum number in a list."""
    return max(numbers)

def list_min(numbers):
    """Returns the minimum number in a list."""
    return min(numbers)


try:
    user_input = input("Enter numbers separated by space: ")
    numbers = [float(x) for x in user_input.split()]

    print("Choose operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = int(input("Enter choice: "))

    if choice == 1:
        print("Sum:", list_sum(numbers))
    elif choice == 2:
        print("Average:", list_average(numbers))
    elif choice == 3:
        print("Maximum:", list_max(numbers))
    elif choice == 4:
        print("Minimum:", list_min(numbers))
    else:
        print("Invalid choice")

except ValueError:
    print("Invalid input. Please enter numbers only.")
except ZeroDivisionError:
    print("List cannot be empty.")

Enter numbers separated by space: 2 4 6 8 10 12
Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice: 2
Average: 7.0


Task 4.2 — List Manipulation

Extract Every Other Element

In [5]:
def extract_every_other(lst):

    return lst[::2]


# User input
user_input = input("Enter numbers separated by space: ")

# Convert input string to list of integers
numbers = [int(x) for x in user_input.split()]

# Call function
result = extract_every_other(numbers)

print("Original list:", numbers)
print("Every other element:", result)

Enter numbers separated by space: 1 2 3 4 5
Original list: [1, 2, 3, 4, 5]
Every other element: [1, 3, 5]


2. Slice a Sublist

In [6]:
def get_sublist(lst, start, end):

    return lst[start:end+1]


# User input for list
user_input = input("Enter numbers separated by space: ")
numbers = [int(x) for x in user_input.split()]

# User input for indices
start = int(input("Enter start index: "))
end = int(input("Enter end index: "))

# Call function
result = get_sublist(numbers, start, end)

print("Original list:", numbers)
print("Sublist:", result)

Enter numbers separated by space: 1 4 7
Enter start index: 1
Enter end index: 2
Original list: [1, 4, 7]
Sublist: [4, 7]


Reverse a List Using Slicing

In [7]:
def reverse_list(lst):
    """
    Returns the reversed list using slicing.
    """
    return lst[::-1]


# User input
user_input = input("Enter numbers separated by space: ")

# Convert input into list
numbers = [int(x) for x in user_input.split()]

# Call function
result = reverse_list(numbers)

print("Original list:", numbers)
print("Reversed list:", result)

Enter numbers separated by space: 1 2 3 4 5
Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements

In [8]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list using slicing.
    """
    return lst[1:-1]


# User input
user_input = input("Enter numbers separated by space: ")
numbers = [int(x) for x in user_input.split()]

result = remove_first_last(numbers)

print("Original list:", numbers)
print("List without first and last elements:", result)

Enter numbers separated by space: 5 4 3 2 1
Original list: [5, 4, 3, 2, 1]
List without first and last elements: [4, 3, 2]


5. Get the First n Elements

In [9]:
def get_first_n(lst, n):
    """
    Returns the first n elements of a list using slicing.
    """
    return lst[:n]


# User input
user_input = input("Enter numbers separated by space: ")
numbers = [int(x) for x in user_input.split()]

n = int(input("Enter value of n: "))

result = get_first_n(numbers, n)

print("Original list:", numbers)
print("First", n, "elements:", result)

Enter numbers separated by space: 2 3 4 5 6 7
Enter value of n: 2
Original list: [2, 3, 4, 5, 6, 7]
First 2 elements: [2, 3]


6. Extract the Last n Elements

In [10]:
def get_last_n(lst, n):
    """
    Returns the last n elements of a list using slicing.
    """
    return lst[-n:]


# User input
user_input = input("Enter numbers separated by space: ")
numbers = [int(x) for x in user_input.split()]

n = int(input("Enter value of n: "))

result = get_last_n(numbers, n)

print("Original list:", numbers)
print("Last", n, "elements:", result)

Enter numbers separated by space: 1 2 3 4 5
Enter value of n: 3
Original list: [1, 2, 3, 4, 5]
Last 3 elements: [3, 4, 5]


7. Extract Elements in Reverse Order

In [11]:
def reverse_skip(lst):
    """
    Returns every second element starting from the second-to-last element moving backward.
    """
    return lst[-2::-2]


# User input
user_input = input("Enter numbers separated by space: ")
numbers = [int(x) for x in user_input.split()]

result = reverse_skip(numbers)

print("Original list:", numbers)
print("Reverse skip elements:", result)

Enter numbers separated by space: 1 2 3 4 5
Original list: [1, 2, 3, 4, 5]
Reverse skip elements: [4, 2]


4.3 Exercise on Nested List:

1. Flatten a Nested List

In [12]:
def flatten(lst):
    """
    Flattens a nested list (one level) into a single list.
    """
    result = []
    for i in lst:
        if isinstance(i, list):
            result.extend(i)
        else:
            result.append(i)
    return result

# Example
nested_list = [[1, 2], [3, 4], [5]]
print("Flattened list:", flatten(nested_list))

Flattened list: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements

In [13]:
def access_nested_element(lst, indices):
    """
    Returns the element from a nested list using a list of indices.
    """
    element = lst
    for i in indices:
        element = element[i]
    return element

# Example
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
print("Accessed element:", access_nested_element(lst, indices))

Accessed element: 6


3. Sum of All Elements in a Nested List

In [14]:
def sum_nested(lst):
    """
    Returns the sum of all numbers in a nested list, any depth.
    """
    total = 0
    for i in lst:
        if isinstance(i, list):
            total += sum_nested(i)
        else:
            total += i
    return total

# Example
nested_list = [[1, 2], [3, [4, 5]], 6]
print("Sum of all elements:", sum_nested(nested_list))

Sum of all elements: 21


4. Remove Specific Element from a Nested List

In [15]:
def remove_element(lst, elem):
    """
    Removes all occurrences of elem from a nested list.
    """
    result = []
    for i in lst:
        if isinstance(i, list):
            result.append(remove_element(i, elem))
        elif i != elem:
            result.append(i)
    return result

# Example
nested_list = [[1, 2], [3, 2], [4, 5]]
elem = 2
print("List after removal:", remove_element(nested_list, elem))

List after removal: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List

In [16]:
def find_max(lst):
    """
    Finds the maximum element in a nested list.
    """
    max_val = float('-inf')
    for i in lst:
        if isinstance(i, list):
            max_val = max(max_val, find_max(i))
        else:
            max_val = max(max_val, i)
    return max_val

# Example
nested_list = [[1, 2], [3, [4, 5]], 6]
print("Maximum element:", find_max(nested_list))

Maximum element: 6


6. Count Occurrences of an Element in a Nested List

In [17]:
def count_occurrences(lst, elem):
    """
    Counts how many times elem occurs in a nested list.
    """
    count = 0
    for i in lst:
        if isinstance(i, list):
            count += count_occurrences(i, elem)
        elif i == elem:
            count += 1
    return count

# Example
nested_list = [[1, 2], [2, 3], [2, 4]]
elem = 2
print("Occurrences of", elem, ":", count_occurrences(nested_list, elem))

Occurrences of 2 : 3


7. Flatten a List of Lists of Lists

In [18]:
def deep_flatten(lst):
    """
    Flattens a nested list of any depth into a single list.
    """
    result = []
    for i in lst:
        if isinstance(i, list):
            result.extend(deep_flatten(i))
        else:
            result.append(i)
    return result

# Example
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print("Deep flattened list:", deep_flatten(nested_list))

Deep flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average

In [19]:
def average_nested(lst):
    """
    Returns the average of all elements in a nested list.
    """
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

# Example
nested_list = [[1, 2], [3, 4], [5, 6]]
print("Average:", average_nested(nested_list))

Average: 3.5


5 About a Numpy.

Problem 1: Array Creation

In [20]:
import numpy as np

In [21]:
# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2,2))
print("Empty Array 2x2:\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4,2))
print("\nAll Ones Array 4x2:\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
fill_array = np.full((3,3), 7)   # Example fill value = 7
print("\nArray filled with 7:\n", fill_array)

# 4. Return a new array of zeros with same shape and type as a given array
arr = np.array([[1,2],[3,4]])
zeros_like_arr = np.zeros_like(arr)
print("\nZeros like arr:\n", zeros_like_arr)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_arr = np.ones_like(arr)
print("\nOnes like arr:\n", ones_like_arr)

# 6. Convert an existing list to numpy array
new_list = [1,2,3,4]
np_array = np.array(new_list)
print("\nConverted NumPy Array:\n", np_array)

Empty Array 2x2:
 [[3.98786122e-315 0.00000000e+000]
 [6.69000878e-310 3.97848638e-315]]

All Ones Array 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like arr:
 [[0 0]
 [0 0]]

Ones like arr:
 [[1 1]
 [1 1]]

Converted NumPy Array:
 [1 2 3 4]


Problem 2: Array Manipulation, Ranges, Indexing

In [22]:
# 1. Array values ranging from 10 to 49
range_array = np.arange(10,50)
print("\nArray 10 to 49:\n", range_array)

# 2. 3x3 matrix values 0 to 8
matrix_3x3 = np.arange(9).reshape(3,3)
print("\n3x3 Matrix 0-8:\n", matrix_3x3)

# 3. 3x3 identity matrix
identity_3x3 = np.eye(3)
print("\nIdentity Matrix 3x3:\n", identity_3x3)

# 4. Random array of size 30 and mean
rand_array = np.random.random(30)
print("\nMean of random array:", rand_array.mean())

# 5. 10x10 random array, find min and max
rand_10x10 = np.random.random((10,10))
print("\nMin:", rand_10x10.min(), "Max:", rand_10x10.max())

# 6. Zero array size 10, replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array with 5th element 1:\n", zero_array)

# 7. Reverse array arr = [1,2,0,0,4,0]
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

# 8. 2D array with 1 on border and 0 inside
border_array = np.ones((5,5))
border_array[1:-1,1:-1] = 0
print("\nBorder array:\n", border_array)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8,8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard:\n", checkerboard)


Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix 0-8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity Matrix 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of random array: 0.4738259514408316

Min: 0.00318902800514842 Max: 0.9985583264580555

Zero array with 5th element 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed Array:
 [0 4 0 0 2 1]

Border array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

8x8 Checkerboard:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem 3: Array Operations

In [23]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add
print("\nAdd x + y:\n", x + y)

# 2. Subtract
print("\nSubtract x - y:\n", x - y)

# 3. Multiply by integer (e.g., 3)
print("\nMultiply x * 3:\n", x*3)

# 4. Square each element
print("\nSquare of x:\n", x**2)

# 5. Dot products
print("\nDot product v.w:", np.dot(v,w))
print("Dot product x.v:", np.dot(x,v))
print("Dot product x.y:\n", np.dot(x,y))

# 6. Concatenate
print("\nConcatenate x and y along row:\n", np.concatenate((x,y), axis=0))
print("Concatenate v and w along column:\n", np.vstack((v,w)).T)

# 7. Concatenate x and v -> will raise error
try:
    print("\nConcatenate x and v:\n", np.concatenate((x,v), axis=0))
except ValueError as e:
    print("Error:", e, "-> Cannot concatenate different shapes")


Add x + y:
 [[ 6  8]
 [10 13]]

Subtract x - y:
 [[-4 -4]
 [-4 -3]]

Multiply x * 3:
 [[ 3  6]
 [ 9 15]]

Square of x:
 [[ 1  4]
 [ 9 25]]

Dot product v.w: 219
Dot product x.v: [29 77]
Dot product x.y:
 [[19 22]
 [50 58]]

Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [[ 9 11]
 [10 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s) -> Cannot concatenate different shapes


Problem 4: Matrix Operations

In [24]:
import numpy as np

# ===============================
# Matrix Operations
# ===============================

# Given matrices
A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# -------------------------------
# 1. Prove A * A^-1 = I
# -------------------------------
A_inv = np.linalg.inv(A)  # Compute inverse of A
identity_check = np.dot(A, A_inv)
print("\n1. A * A^-1 =\n", identity_check)

# Check if approximately equal to identity
print("Is approximately identity?", np.allclose(identity_check, np.eye(2)))

# -------------------------------
# 2. Prove AB != BA
# -------------------------------
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\n2. AB =\n", AB)
print("BA =\n", BA)
print("AB == BA?", np.array_equal(AB, BA))  # False, non-commutative

# -------------------------------
# 3. Prove (AB)^T = B^T * A^T
# -------------------------------
print("\n3. (AB)^T =\n", AB.T)
print("B^T * A^T =\n", np.dot(B.T, A.T))
print("Equal?", np.array_equal(AB.T, np.dot(B.T, A.T)))  # True

# -------------------------------
# 4. Solve system of linear equations
# Equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9
# -------------------------------

# Coefficient matrix
A_matrix = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3, 1, -1]])

# Constants vector
B_vector = np.array([-1, -3, 9])

# Solve using inverse
X_inverse = np.dot(np.linalg.inv(A_matrix), B_vector)
print("\nSolution using inverse method [x, y, z]:", X_inverse)

# Solve using np.linalg.solve (more stable)
X_solve = np.linalg.solve(A_matrix, B_vector)
print("Solution using np.linalg.solve [x, y, z]:", X_solve)

Matrix A:
 [[3 4]
 [7 8]]
Matrix B:
 [[5 3]
 [2 1]]

1. A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is approximately identity? True

2. AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB == BA? False

3. (AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
Equal? True

Solution using inverse method [x, y, z]: [ 2.  1. -2.]
Solution using np.linalg.solve [x, y, z]: [ 2.  1. -2.]
